exports.CAUSE_OF_DEATH = [
  'right at the heart! Gae bolg style, bitches.',
  'right at the neck! Blood starts squirting everywhere.',
  'right at the knee! No more adventures for this lad...',
  'right at the family jewels! Ouch...Ramsay Bolton would be proud.',
  'square at the head! OOOOOOH, H-H-H-HEADSHOT! YOU CAN DANCE ALL DAY!',
  'by shooting the bullet at a metal wall... which ricocheted to a metal street sign... which finally ricocheted to the head.',
  'by throwing the gun at the floor, causing the trigger to go off and miraculously hit.',
  'with a crossbow. What???  I thought this was a gun duel... Anyway.',
  'with a spear at the chest. THIS IS MADNESS!',
  'with LOVE ARROW SHOOT!!!',
  'with a smartphone camera.  Then proceeds to shoot with a regular pistol.',
  'with a railgun, creating a large hole in the body.',
  'with a nerf gun...full of gasoline.  Then throws a lit match.',
  'while doing a somersault! WATCH THIS!',
  'with a flamethrower, BURN BABY BURN!!!',
  'with a nail gun!  You can say that was...crafty. *Sunglasses*',
  'with the holy words from \'Fifty Shades of Grey\'!  Ears start bleeding!',
  'with a paper plane laced with ricin poison.',
  'right at the hand with the gun, causing that gun to misfire and explode!',
  'with dysentery!'
];