export const PLAYER_ADDED = 'PLAYER_ADDED';
export const PLAYER_REMOVED = 'PLAYER_REMOVED';
export const PLAYER_ALREADY_IN_SESSION = 'PLAYER_ALREADY_IN_SESSION';
export const PLAYER_DOES_NOT_EXIST = 'PLAYER_DOES_NOT_EXIST';
export const SESSION_CREATED = 'SESSION_CREATED';
export const SESSION_FULL = 'SESSION_FULL';
export const SESSION_REMOVED = 'SESSION_REMOVED';
export const SESSION_DOES_NOT_EXIST = 'SESSION_DOES_NOT_EXIST';