exports.PLAYER_ADDED = 'PLAYER_ADDED';
exports.PLAYER_REMOVED = 'PLAYER_REMOVED';
exports.PLAYER_ALREADY_IN_SESSION = 'PLAYER_ALREADY_IN_SESSION';
exports.PLAYER_DOES_NOT_EXIST = 'PLAYER_DOES_NOT_EXIST';
exports.SESSION_CREATED = 'SESSION_CREATED';
exports.SESSION_FULL = 'SESSION_FULL';
exports.SESSION_REMOVED = 'SESSION_REMOVED';
exports.SESSION_DOES_NOT_EXIST = 'SESSION_DOES_NOT_EXIST';